## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    url: jdbc:mysql://${MYSQLHOST}/freedb_ecommerceapp?createDatabaseIfNotExist=true
    platform: mysql
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
#    generate-ddl: false
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.MySQL8Dialect



  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: ecommerceApplication
jwtExpiration: 86400
